version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: eldar
      POSTGRES_PASSWORD: mirzabekov
      POSTGRES_DB: nest_jwt

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
